// <auto-generated />
using System;
using Authentication.Repositories;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Authentication.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.4");

            modelBuilder.Entity("Authentication.Model.Employee", b =>
                {
                    b.Property<int>("EmployeeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("EmployeeID");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("EmployeeName")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("TEXT");

                    b.Property<string>("Gender")
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("HireDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("JobTitle")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginID")
                        .HasMaxLength(256)
                        .IsUnicode(false)
                        .HasColumnType("TEXT");

                    b.Property<string>("MaritalStatus")
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("NationalIDNumber")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("RowGuid")
                        .IsUnicode(false)
                        .HasColumnType("TEXT");

                    b.Property<short>("SickLeaveHours")
                        .HasColumnType("INTEGER");

                    b.Property<short>("VacationHours")
                        .HasColumnType("INTEGER");

                    b.HasKey("EmployeeID");

                    b.ToTable("Employee", (string)null);

                    b.HasData(
                        new
                        {
                            EmployeeID = 1,
                            BirthDate = new DateTime(1969, 1, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeName = "Michael Westover",
                            Gender = "M",
                            HireDate = new DateTime(2009, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            JobTitle = "Vice President of Sales",
                            LoginID = "adventure-works\\ken0",
                            MaritalStatus = "S",
                            ModifiedDate = new DateTime(2014, 6, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NationalIDNumber = "295847284",
                            RowGuid = new Guid("f01251e5-96a3-448d-981e-0f99d789110d"),
                            SickLeaveHours = (short)69,
                            VacationHours = (short)99
                        },
                        new
                        {
                            EmployeeID = 2,
                            BirthDate = new DateTime(1971, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeName = "Raeann Santos",
                            Gender = "F",
                            HireDate = new DateTime(2008, 1, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            JobTitle = "Vice President of Engineering",
                            LoginID = "adventure-works\\terri0",
                            MaritalStatus = "S",
                            ModifiedDate = new DateTime(2014, 6, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NationalIDNumber = "245797967",
                            RowGuid = new Guid("45e8f437-670d-4409-93cb-f9424a40d6ee"),
                            SickLeaveHours = (short)20,
                            VacationHours = (short)1
                        },
                        new
                        {
                            EmployeeID = 3,
                            BirthDate = new DateTime(1974, 11, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmployeeName = "Pamela Wambsgans",
                            Gender = "M",
                            HireDate = new DateTime(2007, 11, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            JobTitle = "Engineering Manager",
                            LoginID = "adventure-works\\roberto0",
                            MaritalStatus = "M",
                            ModifiedDate = new DateTime(2014, 6, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NationalIDNumber = "509647174",
                            RowGuid = new Guid("9bbbfb2c-efbb-4217-9ab7-f97689328841"),
                            SickLeaveHours = (short)21,
                            VacationHours = (short)2
                        });
                });

            modelBuilder.Entity("Authentication.Model.UserInfo", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(60)
                        .IsUnicode(false)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("TEXT");

                    b.Property<string>("UserName")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("TEXT");

                    b.HasKey("UserId");

                    b.ToTable("UserInfo", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            CreatedDate = new DateTime(2024, 4, 24, 14, 47, 58, 207, DateTimeKind.Unspecified),
                            DisplayName = "Kemi Mo",
                            Email = "admin@abc.com",
                            Password = "$admin@2022",
                            UserName = "Admin"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
